# Generated by Django 5.2 on 2026-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexamresult',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, help_text='Time taken to complete the exam in seconds'),
        ),
    ]
