# Generated by Django 5.2 on 2026-05-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0005_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
