# Generated by Django 5.2 on 2026-05-21 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0006_basicprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_interviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('total_interviews', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_category', models.ManyToManyField(related_name='interviewers', to='teacherhire.classcategory')),
                ('subject', models.ManyToManyField(related_name='interviewers', to='teacherhire.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='teacherhire.interviewerprofile')),
            ],
        ),
    ]
