# Generated by Django 5.2 on 2026-05-23 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0007_customuser_is_interviewer_interview_interviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], default='Backend', max_length=50)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
